import { readdirSync, writeFileSync, copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const publicDir = join(process.cwd(), ".output", "public");
const assetsDir = join(publicDir, "assets");
const htaccessSrc = join(process.cwd(), "public", ".htaccess");
const indexPath = join(publicDir, "index.html");
const shellPath = join(publicDir, "_shell.html");

if (!existsSync(publicDir)) {
  console.error("Missing .output/public — run vite build first.");
  process.exit(1);
}

mkdirSync(publicDir, { recursive: true });

// Prefer the SPA shell generated by TanStack Start.
if (existsSync(shellPath) && !existsSync(indexPath)) {
  copyFileSync(shellPath, indexPath);
  console.log("Copied _shell.html → index.html");
}

// If the build already wrote a real index.html, keep it.
// Otherwise synthesize one that loads the hashed client bundles.
if (!existsSync(indexPath)) {
  if (!existsSync(assetsDir)) {
    console.error("Missing .output/public/assets — cannot build fallback index.html.");
    process.exit(1);
  }

  const files = readdirSync(assetsDir);
  const js = files.find((f) => /^index-.*\.js$/.test(f));
  const css = files.find((f) => /^styles-.*\.css$/.test(f));

  if (!js || !css) {
    console.error("Could not find index-*.js or styles-*.css in assets.");
    process.exit(1);
  }

  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BluFin Capital Advisory</title>
    <link rel="icon" href="/favicon.ico" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="stylesheet" crossorigin href="/assets/${css}" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" crossorigin src="/assets/${js}"></script>
  </body>
</html>
`;
  writeFileSync(indexPath, html, "utf8");
  console.log(`Wrote fallback index.html (js=${js}, css=${css})`);
} else {
  const size = readFileSync(indexPath).byteLength;
  console.log(`Using existing index.html (${size} bytes)`);
}

if (existsSync(htaccessSrc)) {
  copyFileSync(htaccessSrc, join(publicDir, ".htaccess"));
  console.log("Copied .htaccess");
}

for (const file of ["robots.txt", "sitemap.xml"]) {
  const src = join(process.cwd(), "public", file);
  if (existsSync(src)) {
    copyFileSync(src, join(publicDir, file));
    console.log(`Copied ${file}`);
  }
}
