/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatWeDoIndexRouteImport } from './routes/what-we-do/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as WhatWeDoMaDealsRouteImport } from './routes/what-we-do/ma-deals'
import { Route as WhatWeDoListingCapitalMarketsRouteImport } from './routes/what-we-do/listing-capital-markets'
import { Route as WhatWeDoCorporateFinanceRouteImport } from './routes/what-we-do/corporate-finance'
import { Route as AboutGovernanceRouteImport } from './routes/about/governance'
import { Route as AboutCompanyProfileRouteImport } from './routes/about/company-profile'
import { Route as AboutTeamIndexRouteImport } from './routes/about/team/index'
import { Route as AboutTeamBoardRouteImport } from './routes/about/team/board'
import { Route as AboutTeamAppointedRouteImport } from './routes/about/team/appointed'
import { Route as AboutTeamMemberIdRouteImport } from './routes/about/team/$memberId'

const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoIndexRoute = WhatWeDoIndexRouteImport.update({
  id: '/what-we-do/',
  path: '/what-we-do/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoMaDealsRoute = WhatWeDoMaDealsRouteImport.update({
  id: '/what-we-do/ma-deals',
  path: '/what-we-do/ma-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoListingCapitalMarketsRoute =
  WhatWeDoListingCapitalMarketsRouteImport.update({
    id: '/what-we-do/listing-capital-markets',
    path: '/what-we-do/listing-capital-markets',
    getParentRoute: () => rootRouteImport,
  } as any)
const WhatWeDoCorporateFinanceRoute =
  WhatWeDoCorporateFinanceRouteImport.update({
    id: '/what-we-do/corporate-finance',
    path: '/what-we-do/corporate-finance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/about/governance',
  path: '/about/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCompanyProfileRoute = AboutCompanyProfileRouteImport.update({
  id: '/about/company-profile',
  path: '/about/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamIndexRoute = AboutTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutTeamRoute,
} as any)
const AboutTeamBoardRoute = AboutTeamBoardRouteImport.update({
  id: '/about/team/board',
  path: '/about/team/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamAppointedRoute = AboutTeamAppointedRouteImport.update({
  id: '/about/team/appointed',
  path: '/about/team/appointed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamMemberIdRoute = AboutTeamMemberIdRouteImport.update({
  id: '/about/team/$memberId',
  path: '/about/team/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/portal': typeof PortalRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/track-record': typeof TrackRecordRoute
  '/about/company-profile': typeof AboutCompanyProfileRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/what-we-do/corporate-finance': typeof WhatWeDoCorporateFinanceRoute
  '/what-we-do/listing-capital-markets': typeof WhatWeDoListingCapitalMarketsRoute
  '/what-we-do/ma-deals': typeof WhatWeDoMaDealsRoute
  '/about/': typeof AboutIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
  '/about/team/$memberId': typeof AboutTeamMemberIdRoute
  '/about/team/appointed': typeof AboutTeamAppointedRoute
  '/about/team/board': typeof AboutTeamBoardRoute
  '/about/team/': typeof AboutTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/portal': typeof PortalRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/track-record': typeof TrackRecordRoute
  '/about/company-profile': typeof AboutCompanyProfileRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/what-we-do/corporate-finance': typeof WhatWeDoCorporateFinanceRoute
  '/what-we-do/listing-capital-markets': typeof WhatWeDoListingCapitalMarketsRoute
  '/what-we-do/ma-deals': typeof WhatWeDoMaDealsRoute
  '/about': typeof AboutIndexRoute
  '/what-we-do': typeof WhatWeDoIndexRoute
  '/about/team/$memberId': typeof AboutTeamMemberIdRoute
  '/about/team/appointed': typeof AboutTeamAppointedRoute
  '/about/team/board': typeof AboutTeamBoardRoute
  '/about/team': typeof AboutTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/portal': typeof PortalRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/track-record': typeof TrackRecordRoute
  '/about/company-profile': typeof AboutCompanyProfileRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/what-we-do/corporate-finance': typeof WhatWeDoCorporateFinanceRoute
  '/what-we-do/listing-capital-markets': typeof WhatWeDoListingCapitalMarketsRoute
  '/what-we-do/ma-deals': typeof WhatWeDoMaDealsRoute
  '/about/': typeof AboutIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
  '/about/team/$memberId': typeof AboutTeamMemberIdRoute
  '/about/team/appointed': typeof AboutTeamAppointedRoute
  '/about/team/board': typeof AboutTeamBoardRoute
  '/about/team/': typeof AboutTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portal'
    | '/search'
    | '/services'
    | '/track-record'
    | '/about/company-profile'
    | '/about/governance'
    | '/what-we-do/corporate-finance'
    | '/what-we-do/listing-capital-markets'
    | '/what-we-do/ma-deals'
    | '/about/'
    | '/what-we-do/'
    | '/about/team/$memberId'
    | '/about/team/appointed'
    | '/about/team/board'
    | '/about/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portal'
    | '/search'
    | '/services'
    | '/track-record'
    | '/about/company-profile'
    | '/about/governance'
    | '/what-we-do/corporate-finance'
    | '/what-we-do/listing-capital-markets'
    | '/what-we-do/ma-deals'
    | '/about'
    | '/what-we-do'
    | '/about/team/$memberId'
    | '/about/team/appointed'
    | '/about/team/board'
    | '/about/team'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/portal'
    | '/search'
    | '/services'
    | '/track-record'
    | '/about/company-profile'
    | '/about/governance'
    | '/what-we-do/corporate-finance'
    | '/what-we-do/listing-capital-markets'
    | '/what-we-do/ma-deals'
    | '/about/'
    | '/what-we-do/'
    | '/about/team/$memberId'
    | '/about/team/appointed'
    | '/about/team/board'
    | '/about/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  PortalRoute: typeof PortalRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  TrackRecordRoute: typeof TrackRecordRoute
  AboutCompanyProfileRoute: typeof AboutCompanyProfileRoute
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  WhatWeDoCorporateFinanceRoute: typeof WhatWeDoCorporateFinanceRoute
  WhatWeDoListingCapitalMarketsRoute: typeof WhatWeDoListingCapitalMarketsRoute
  WhatWeDoMaDealsRoute: typeof WhatWeDoMaDealsRoute
  AboutIndexRoute: typeof AboutIndexRoute
  WhatWeDoIndexRoute: typeof WhatWeDoIndexRoute
  AboutTeamMemberIdRoute: typeof AboutTeamMemberIdRoute
  AboutTeamAppointedRoute: typeof AboutTeamAppointedRoute
  AboutTeamBoardRoute: typeof AboutTeamBoardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/': {
      id: '/what-we-do/'
      path: '/what-we-do'
      fullPath: '/what-we-do/'
      preLoaderRoute: typeof WhatWeDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/ma-deals': {
      id: '/what-we-do/ma-deals'
      path: '/what-we-do/ma-deals'
      fullPath: '/what-we-do/ma-deals'
      preLoaderRoute: typeof WhatWeDoMaDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/listing-capital-markets': {
      id: '/what-we-do/listing-capital-markets'
      path: '/what-we-do/listing-capital-markets'
      fullPath: '/what-we-do/listing-capital-markets'
      preLoaderRoute: typeof WhatWeDoListingCapitalMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/corporate-finance': {
      id: '/what-we-do/corporate-finance'
      path: '/what-we-do/corporate-finance'
      fullPath: '/what-we-do/corporate-finance'
      preLoaderRoute: typeof WhatWeDoCorporateFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/governance': {
      id: '/about/governance'
      path: '/about/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/company-profile': {
      id: '/about/company-profile'
      path: '/about/company-profile'
      fullPath: '/about/company-profile'
      preLoaderRoute: typeof AboutCompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team/': {
      id: '/about/team/'
      path: '/'
      fullPath: '/about/team/'
      preLoaderRoute: typeof AboutTeamIndexRouteImport
      parentRoute: typeof AboutTeamRoute
    }
    '/about/team/board': {
      id: '/about/team/board'
      path: '/about/team/board'
      fullPath: '/about/team/board'
      preLoaderRoute: typeof AboutTeamBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team/appointed': {
      id: '/about/team/appointed'
      path: '/about/team/appointed'
      fullPath: '/about/team/appointed'
      preLoaderRoute: typeof AboutTeamAppointedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team/$memberId': {
      id: '/about/team/$memberId'
      path: '/about/team/$memberId'
      fullPath: '/about/team/$memberId'
      preLoaderRoute: typeof AboutTeamMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  PortalRoute: PortalRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  TrackRecordRoute: TrackRecordRoute,
  AboutCompanyProfileRoute: AboutCompanyProfileRoute,
  AboutGovernanceRoute: AboutGovernanceRoute,
  WhatWeDoCorporateFinanceRoute: WhatWeDoCorporateFinanceRoute,
  WhatWeDoListingCapitalMarketsRoute: WhatWeDoListingCapitalMarketsRoute,
  WhatWeDoMaDealsRoute: WhatWeDoMaDealsRoute,
  AboutIndexRoute: AboutIndexRoute,
  WhatWeDoIndexRoute: WhatWeDoIndexRoute,
  AboutTeamMemberIdRoute: AboutTeamMemberIdRoute,
  AboutTeamAppointedRoute: AboutTeamAppointedRoute,
  AboutTeamBoardRoute: AboutTeamBoardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
